title:              Bianca and Ricardo say YES
email:              ricardothoma@hotmail.de
description:        Informationen zur Hochzeit
author:             Ricardo Thoma
baseurl:            "https://ricotoom.github.io"
url:                "https://ricotoom.github.io/index.html"

# Social Profiles
twitter_username:   
github_username:    
facebook_username: 
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "index.html"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
